### ISSUE TITLE
HHVM no longer has a persistent resource store (this no longer compiles)

### ISSUE THREAD

**Issue by thedjnK** [duxet/hhvm-zmq#4]
Two issues when trying to compile this for newer versions of HHVM;
1) zmq.cpp line 160 needs NEWOBJ() changed to newres<>
2) g_persistentResources has been completely removed from HHVM... I'm not sure what would replace it, this no longer compiles as a result.

**Comment by tboronczyk** [comment]
This affects me too. I'll poke around and if I can find a solution I'll do a pull request. Otherwise, I'd be happy if @duxet can find time in his schedule to review the issue.

**Comment by duxet** [comment]
The problem is that i am not even sure if the previous way of storing the connection was right, i tried to do it same way as other extensions do :P

I noticed that somebody has started another project: https://github.com/hhvm-zmq/hhvm-zmq - it seems to be more advanced. Has anyone tried it already?

**Comment by thedjnK** [comment]
I haven't tried it purely based on the comment 'This is a work in progress, and is not currently usable.'

**Comment by kilyo** [comment]
I managed to get this to compile today on HHVM 3.6.0. With a dependency on libzmq4. I borrowed the persistance from mysql. I hope to have a pull this weekend.
